### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'D:/'

### ISSUE THREAD

**Issue by Senethys** [blueimp/atom-open-terminal-here#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [open-terminal-here](https://github.com/blueimp/atom-open-terminal-here) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'D:\'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat 'D:\'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at start (fs.js:1515:10)
    at Object.realpathSync (fs.js:1503:3)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at open (/packages/open-terminal-here/index.coffee:40:24)
    at /packages/open-terminal-here/index.coffee:65:9)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:19.7.0 open-terminal-here:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
open-terminal-here 2.3.1 
```

**Comment by blueimp** [comment]
Thanks for your report @Senethys 
At the moment I do not have the time resources to test on Windows, so any pull requests are welcome.
